---
abstract: 'The Sidef Programming Language'
author:
  - 'Daniel Șuteu   (<trizen@cpan.org>)'
  - 'Ioana Fălcușan (<ioanaflavia@gmail.com>)'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sidef
provides:
  Sidef:
    file: lib/Sidef.pm
    version: '3.96'
  Sidef::Deparse::Perl:
    file: lib/Sidef/Deparse/Perl.pm
  Sidef::Deparse::Sidef:
    file: lib/Sidef/Deparse/Sidef.pm
  Sidef::Math::Math:
    file: lib/Sidef/Math/Math.pm
  Sidef::Module::Func:
    file: lib/Sidef/Module/Func.pm
  Sidef::Module::OO:
    file: lib/Sidef/Module/OO.pm
  Sidef::Object::Convert:
    file: lib/Sidef/Object/Convert.pm
  Sidef::Object::Enumerator:
    file: lib/Sidef/Object/Enumerator.pm
  Sidef::Object::Lazy:
    file: lib/Sidef/Object/Lazy.pm
  Sidef::Object::LazyMethod:
    file: lib/Sidef/Object/LazyMethod.pm
  Sidef::Object::Object:
    file: lib/Sidef/Object/Object.pm
  Sidef::Optimizer:
    file: lib/Sidef/Optimizer.pm
  Sidef::Parser:
    file: lib/Sidef/Parser.pm
  Sidef::Perl::Perl:
    file: lib/Sidef/Perl/Perl.pm
  Sidef::Sys::Sig:
    file: lib/Sidef/Sys/Sig.pm
  Sidef::Sys::Sys:
    file: lib/Sidef/Sys/Sys.pm
  Sidef::Time::Date:
    file: lib/Sidef/Time/Date.pm
  Sidef::Time::Time:
    file: lib/Sidef/Time/Time.pm
  Sidef::Types::Array::Array:
    file: lib/Sidef/Types/Array/Array.pm
  Sidef::Types::Array::Matrix:
    file: lib/Sidef/Types/Array/Matrix.pm
  Sidef::Types::Array::Pair:
    file: lib/Sidef/Types/Array/Pair.pm
  Sidef::Types::Array::Vector:
    file: lib/Sidef/Types/Array/Vector.pm
  Sidef::Types::Block::Block:
    file: lib/Sidef/Types/Block/Block.pm
  Sidef::Types::Block::Fork:
    file: lib/Sidef/Types/Block/Fork.pm
  Sidef::Types::Block::Try:
    file: lib/Sidef/Types/Block/Try.pm
  Sidef::Types::Bool::Bool:
    file: lib/Sidef/Types/Bool/Bool.pm
  Sidef::Types::Glob::Backtick:
    file: lib/Sidef/Types/Glob/Backtick.pm
  Sidef::Types::Glob::Dir:
    file: lib/Sidef/Types/Glob/Dir.pm
  Sidef::Types::Glob::DirHandle:
    file: lib/Sidef/Types/Glob/DirHandle.pm
  Sidef::Types::Glob::File:
    file: lib/Sidef/Types/Glob/File.pm
  Sidef::Types::Glob::FileHandle:
    file: lib/Sidef/Types/Glob/FileHandle.pm
  Sidef::Types::Glob::Pipe:
    file: lib/Sidef/Types/Glob/Pipe.pm
  Sidef::Types::Glob::Socket:
    file: lib/Sidef/Types/Glob/Socket.pm
  Sidef::Types::Glob::SocketHandle:
    file: lib/Sidef/Types/Glob/SocketHandle.pm
  Sidef::Types::Glob::Stat:
    file: lib/Sidef/Types/Glob/Stat.pm
  Sidef::Types::Hash::Hash:
    file: lib/Sidef/Types/Hash/Hash.pm
  Sidef::Types::Null::Null:
    file: lib/Sidef/Types/Null/Null.pm
  Sidef::Types::Number::Complex:
    file: lib/Sidef/Types/Number/Complex.pm
  Sidef::Types::Number::Gauss:
    file: lib/Sidef/Types/Number/Gauss.pm
  Sidef::Types::Number::Mod:
    file: lib/Sidef/Types/Number/Mod.pm
  Sidef::Types::Number::Number:
    file: lib/Sidef/Types/Number/Number.pm
  Sidef::Types::Range::Range:
    file: lib/Sidef/Types/Range/Range.pm
  Sidef::Types::Range::RangeNumber:
    file: lib/Sidef/Types/Range/RangeNumber.pm
  Sidef::Types::Range::RangeString:
    file: lib/Sidef/Types/Range/RangeString.pm
  Sidef::Types::Regex::Match:
    file: lib/Sidef/Types/Regex/Match.pm
  Sidef::Types::Regex::Regex:
    file: lib/Sidef/Types/Regex/Regex.pm
  Sidef::Types::Set::Bag:
    file: lib/Sidef/Types/Set/Bag.pm
  Sidef::Types::Set::Set:
    file: lib/Sidef/Types/Set/Set.pm
  Sidef::Types::String::String:
    file: lib/Sidef/Types/String/String.pm
  Sidef::Variable::GetOpt:
    file: lib/Sidef/Variable/GetOpt.pm
  Sidef::Variable::NamedParam:
    file: lib/Sidef/Variable/NamedParam.pm
recommends:
  Data::Dump: '0'
  Data::Dump::Filtered: '0'
  Digest::MD5: '0'
  Digest::SHA: '0'
  File::Find: '0'
  MIME::Base64: '0'
  Math::Prime::Util: '0.73'
  Term::ReadLine::Gnu: '0'
requires:
  Algorithm::Combinatorics: '0'
  Algorithm::Loops: '0'
  Cwd: '0'
  Encode: '0'
  Fcntl: '0'
  File::Basename: '0'
  File::Copy: '0'
  File::Path: '0'
  File::Spec: '0'
  Getopt::Std: '0'
  List::Util: '1.33'
  Math::GMPq: '0.45'
  Math::GMPz: '0.39'
  Math::MPC: '0'
  Math::MPFR: '3.36'
  Math::Prime::Util::GMP: '0.52'
  Memoize: '0'
  Scalar::Util: '0'
  Socket: '0'
  Term::ReadLine: '0'
  Time::HiRes: '0'
  Time::Piece: '0'
  parent: '0'
  perl: v5.18.0
  utf8: '0'
resources:
  bugtracker: https://github.com/trizen/sidef/issues
  homepage: https://github.com/trizen/sidef
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/trizen/sidef
version: '3.96'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
